### ISSUE TITLE
General inquiry

### ISSUE THREAD

**Issue by mwpowellhtx** [RupertAvery/csharpeval#1]
Hello,

Thank you for the repository and I have a couple of general questions, but could I also contact you offline?

A little about what I am looking for at the moment. I've got some classes that are going to expose at least a private (or protected, or whatever) dynamic object that I want to evaluate and return either a Boolean or Double, yes/no or weight, respectively.

Generally, looking for dynamic support, will either pass a dynamic instance as parameter(s), or should have access to member properties (i.e. as a true compiled Expression). Rich support for operators, math functions, etc, would be helpful; math functions may be nice to have, but definitely a nominally rich set of operators and such.

Don't be too hard on yourself. The organization of the solution could use some help, but as long as it "works" out of the box, that's the first thing. Clean up at your convenience. Generally I look for things like parent-level solution file, code and unit test projects, etc.

Anyway... Thanks so much...

**Comment by RupertAvery** [comment]
Hi,

I'm not sure what you mean by what you are looking for, or organization of
the solution.

You can contact me at rupert.avery@gmail.com.

I'm actually form the Philippines so getting in touch offline is kind of
difficult if you're on the other side of the world.

**Comment by mwpowellhtx** [comment]
No worries, thanks for responding.

I was referring to the location of the Solution file, especially in reference to "core" and "test" assemblies. One trend that has been catching on is to capture a "src" folder, with Solution file, then project directories.

Anyway, to an end user such as myself, I couldn't necessarily tell the difference unless I wanted to submit a PR.

Thanks for the great library...

**Comment by RupertAvery** [comment]
Ah, yes, the folder structure leaves much to be desired.  It's a holdover
from I think Visual Studio 2008, where a solution was created in the same
folder as the project. I'll fix it up, thanks for bringing that to my
attention.
