### ISSUE TITLE
Extend TypeRegistry for custom (or other) types

### ISSUE THREAD

**Issue by mwpowellhtx** [RupertAvery/csharpeval#4]
Such as TimeSpan. Also, believe it or not, I have a use case involving a [BitArray](http://msdn.microsoft.com/en-us/library/system.collections.bitarray.aspx) (don't ask), that I need to be able to support things like its bitwise functions. And at that, I may need to consider an [IComparable](http://msdn.microsoft.com/en-us/library/system.icomparable.aspx) extension to BitArray.

That's also assuming that "simply" extending [TypeRegistry](https://github.com/RupertAvery/csharpeval/blob/fc800603a45306815d7f488652cc7758ac2ed5f4/TypeRegistry.cs) would work in my case, or whether I needed to submit a [PR](http://github.com/RupertAvery/csharpeval/pulls).

**Comment by mwpowellhtx** [comment]
Could potentially virtualize methods like RegisterDefaultTypes in order to extend TypeRegistry into the user space. Not counting any expression level handlers.

**Comment by mwpowellhtx** [comment]
This may be a "non-issue" after all. Preliminary test case:

```C#
var now = new TimeStampedData {TimeStamp = TimeSpan.FromMilliseconds(1000)};
var then = new TimeStampedData {TimeStamp = TimeSpan.FromMilliseconds(500)};

var registry = new TypeRegistry();

registry.RegisterSymbol(@"now", now);
registry.RegisterSymbol(@"then", then);

var ce = new CompiledExpression<bool>(@"now.TimeStamp > then.TimeStamp")
{
    TypeRegistry = registry
};

var result = ce.ScopeCompile<TimeStampedData>();

Debug.Assert(result(now));
```

This was the second test case from a "simple" evaluation of TimeSpan instances.

**Comment by mwpowellhtx** [comment]
Now, with a BitArray wrapper. I've implemented simple equality and the bitwise operators. Here goes nothing:

```C#
var a = new BitArray(new byte[] {0xff, 0xff, 0xff, 0xff});
var b = new BitArray(new byte[] {0x23, 0x45, 0x67, 0x89});

var aex = new BitArrayEx {Array = a};
var bex = new BitArrayEx {Array = b};

var registry = new TypeRegistry();

registry.RegisterSymbol(@"aex", aex);
registry.RegisterSymbol(@"bex", bex);

var ce = new CompiledExpression<bool>(@"(aex & bex) == aex")
{
    TypeRegistry = registry
};

var result = ce.ScopeCompile<BitArrayEx>();

Debug.Assert(result(aex));
```

Note the bitwise And, Equality, and even the parenthesis. Wow I am impressed!

**Comment by RupertAvery** [comment]
Hi,  thanks for your interest in ExpressionEval

 ScopeCompile is actually designed so you don't have to register symbols.  ScopeCompile defines a parameter that acts as the default resolution for symbols in the expression.  The "scope" of the expression if you will.

Registering symbols has the effect of binding their current values/references in the compiled expression.  If you pointed aex to another bitarray and reused the compiled function "result", you would get the old values. The use of a scope is to act as a container for your variables, so you can change the variables outside of the function and not have to recompile the function.

Reusing the compiled function makes a lot of sense if your expression does not change, but your data does.  Compilation is expensive especially if executed in a loop. 

I guess my API isn't too clear.

Oh, by the way, the original documentation is up on http://chsarpeval.codeplex.com

**Comment by mwpowellhtx** [comment]
Good tips, thanks for that.

So, minimum, I would want to consider "refreshing" the TypeRegistry with every pass, but wouldn't necessarily need to recompile the output function. That's awesome. I will try that.

Indeed, some compiled Xml help going with the Nuget would be helpful. Should be easy to include in your Nuspec and with the build.

Anyway, looking forward to what's in store for C# 6...
