### ISSUE TITLE
How to deal with Property with type of "Interface"

### ISSUE THREAD

**Issue by zhaosih** [RupertAvery/csharpeval#8]
code in program.cs is below. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using ExpressionEvaluator;
namespace StrIndex
{
    class Program
    {
        static void Main(string[] args)
        {
            StrIndex s = new StrIndex();
            TryIndex tryIndex=new TryIndex();
            tryIndex.ss =s;
            TypeRegistry tr = new TypeRegistry();
            tr.RegisterDefaultTypes();
            tr.RegisterSymbol("ti", tryIndex);
            CompiledExpression cex = new CompiledExpression("ti.ss[\"x\"].ToString()") { TypeRegistry = tr };
            // here report exception : Cannot resolve member "ToString" on type "IStrIndex
            cex.Eval();
        }
    }

    class TryIndex
    {
        public IStrIndex ss;
    }
    class StrIndex:IStrIndex
    {
        public string this[string name]
        {
            get
            {
                return "xx";
            }
        }

   IEnumerator<string> IEnumerable<string>.GetEnumerator()
   {
       return null;
   }

   System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
   {
       throw new NotImplementedException();
   }
    }

    interface IStrIndex : IEnumerable<string>
    {
        string this[string name]
        {
            get;
        }
    }
}

**Comment by zhaosih** [comment]
Try the AntlPaser branch. Seems work better. but I suggest 

use below code

 if (interfaces.Any(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable<>)))

to replace

 if (interfaces.Any(t => t.IsGenericType && t.GetGenericTypeDefinition() == typeof(IList<>)))

**Comment by RupertAvery** [comment]
I've implemented a better way of handling this by checking if the property has parameters.  It should now work for any types, including IDictionary.
